version: '3.3'

services:
    nginx:
        image: nginx:latest
        ports:
            - "80:80"
            - "8081:8081"
        volumes:
            - ./Nginx/core:/etc/nginx/conf.d
            - ./app:/var/www/app
            - ./Nginx/Logs:/var/log/nginx/
            - ./Nginx/html:/usr/share/nginx/html/
        links:
            - php
    mysql:
        image: mysql:5.7
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=verysecret
            - MYSQL_DATABASE=yii2advanced
            - MYSQL_USER=yii2advanced
            - MYSQL_PASSWORD=secret
        volumes:
            - ./MySQL:/var/lib/mysql
    php:
        build: ./PHP
        container_name: php-fpm
        volumes:
            - ./app:/var/www/app
        links:
            - mysql